### ISSUE TITLE
Site Basepath not updating nginx conf

### ISSUE THREAD

**Issue by LemarinelNet** [andreapollastri/cipi#195]
Hi,

Using Cipi 3.0

I've created a site with default settings : basepath /public/
I need to change the basepath, so I went to site settings, changed basepath to /current/public 
Saved, it is correctly saved on site settings, but when I look on the server nginx site's conf, it is still on /public (not reflecting "current/public").

Thanks

**Comment by andreapollastri** [comment]
Hi @LemarinelNet . Thank You for the issue. This is a site patch API bug. I'll fix it and release in the next 2 days. Thankyou.

**Comment by andreapollastri** [comment]
Hi @LemarinelNet this issue should be solved in Cipi version 3.0.1. Your Control Panel will receive this update automatically this night. Let me know if something goes wrong. Thank You

**Comment by LemarinelNet** [comment]
The base server did update this night, but the slave server is still on a lower build number ?
Is there something to do so the server will update ?

**Comment by andreapollastri** [comment]
No! The issue was related to panel, so if your panel is now at version 3.0.1 is OK.
The server client build was not affected from the basepath bug. It will be updated automatically in case of new PHP versions or similar.
Let me know if the issue is not solved also in version 3.0.1. And thank you again for this bug discovery!

**Comment by LemarinelNet** [comment]
Well I've try to update my site's basepath on the central server, and the slave server nginx conf did not changed !
Thanks for being so quick !

**Comment by andreapollastri** [comment]
Ok! I'll re-check this evening and I'll update you. I'm sorry for the issue! I'll solve it.
The only doubt that I have is that your site is "not aligned" with panel (for the issue).
So suppose that your website started with "public" basepath and then it changed in "" but the issue updated only the panel dB and not the nginx conf... now the panel is trying to find the updated conf in nginx conf and it didn't find it so it will not update it. Yesterday I tried with a "new site" and it worked... now I try to replicate a not aligned scenario. 

I don't know how is your scenario... But I think that if the dB was not aligned to nginx you have to recreate the site, I'm sorry... I'll notice to you a better detail after other tests!

**Comment by LemarinelNet** [comment]
I'll check with a new site, I'll tell you.
Perhaps a workaround would be to surrond root path with special comments so the panel would find it easily like this :

###ROOTPATH
root /home/users/
###ENDROOTPATH

**Comment by LemarinelNet** [comment]
I can confirm that on a new site it works.
Don't worry about my current (not working) site, it was a test ;)

PS : I noticed that the first site conf was a standard file, but the new one is a symbolic link ?

**Comment by andreapollastri** [comment]
Hi, from a last check I notice that my last fix works but it didn't let you to return to an empty basepath from a "filled" basepath so I fixed it. I confirm that new sites correctly works. 

About symbolic link I didn't have the same situation... I really don't know!

**Comment by LemarinelNet** [comment]
Still a bug...
I try to change a site's basepath : 
It sends the correct PATCH http request, with the new basepath I set (seen in dev tools console), but then the web UI refresh and show the previous value (not updated !!)

**Comment by andreapollastri** [comment]
Hi @LemarinelNet what Cipi version are you running? 3.0.8?

**Comment by LemarinelNet** [comment]
Yes! 3.0.8

**Comment by andreapollastri** [comment]
It's really strange, I'm really sorry... let me check and test the current version in the next hours and I'll update the issue tonight or tomorrow!

**Comment by LemarinelNet** [comment]
Ok I'll wait :)

**Comment by andreapollastri** [comment]
Hi @LemarinelNet ... thankyou for the issue. Cipi had a problem on the Site PATCH API endpoint that I solved in current version (3.0.9). Your Cipi panel will be update automatically this night! 
You should not but... if you have any issue with current sites, try to recreate them... anyway if you have problems open an issue and I'll fix it. Thank You for the issue. You are helping to improve Cipi, so really Thank You ;)

**Comment by LemarinelNet** [comment]
It works !!
Thanks

**Comment by LemarinelNet** [comment]
Hi,
Still got the problem on 3.10.0, 
I just created a new site, published contents inside it, changed base path, but nginx conf files still show "/web" path, not using the base path attribute appendix !!
